import {
  LayoutDashboard,
  FolderKanban,
  DollarSign,
  Users,
  Building2,
  MapPin,
  Gavel,
  HardHat,
  Gauge,
  Package,
  TrendingUp,
  KeyRound,
  ShoppingCart,
  Megaphone,
  Target,
  UserCog,
  Scale,
  FileText,
  Boxes,
  Headset,
  Home,
  Bot,
  Landmark,
  DoorOpen,
  Droplets,
  UserSquare,
  ScrollText as ScrollTextFM,
  Banknote,
  AlertOctagon,
  Hammer,
  ShieldPlus,
  Store,
  UserCog as UserCogFM,
  CalendarClock as CalendarClockFM,
  Eye as EyeFM,
  ImagePlus,
  ListChecks,
  Milestone,
  ClipboardList,
  GanttChart,
  PiggyBank,
  BookOpen,
  Receipt,
  CreditCard,
  BarChart3,
  UserPlus,
  MessageSquare,
  CalendarClock,
  Kanban,
  Building,
  Layers,
  Star,
  ClipboardCheck,
  PieChart,
  Map,
  Handshake,
  Search,
  ShieldCheck,
  Truck,
  FileCheck,
  BarChart,
  ShieldAlert,
  AlertTriangle,
  FileEdit,
  Clock,
  Calculator,
  Wrench,
  ArrowLeftRight,
  LineChart,
  Eye,
  History,
  BadgeDollarSign,
  CalendarRange,
  TrendingDown,
  FileWarning,
  Bookmark,
  HandCoins,
  Flag,
  Megaphone as MegaphoneIcon,
  Radio,
  Image,
  Activity,
  Calendar,
  GitBranch,
  Wallet,
  Briefcase,
  UserCheck,
  CalendarDays,
  Plane,
  ScrollText,
  Stamp,
  Gavel as GavelIcon,
  FileKey,
  FolderOpen,
  FilePlus,
  FolderArchive,
  Warehouse,
  ClipboardMinus,
  PackageCheck,
  Ticket,
  Settings,
  Timer,
  Contact,
  Bell,
  MessageCircle,
  FileSpreadsheet,
  UsersRound,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface SubMenuItem {
  path: string;
  label: string;
  icon: LucideIcon;
}

export interface NavModule {
  key: string;
  label: string;
  icon: LucideIcon;
  group: string;
  subItems: SubMenuItem[];
}

export const navModules: NavModule[] = [
  // ==================== CORE ====================
  {
    key: "projects",
    label: "Project Management",
    icon: FolderKanban,
    group: "Core",
    subItems: [
      { path: "/projects/list", label: "Project List", icon: ListChecks },
      { path: "/projects/milestones", label: "Milestones & Phases", icon: Milestone },
      { path: "/projects/tasks", label: "Task Assignments", icon: ClipboardList },
      { path: "/projects/gantt", label: "Gantt / Timeline", icon: GanttChart },
      { path: "/projects/budget-tracking", label: "Budget vs Actual", icon: PiggyBank },
    ],
  },
  {
    key: "finance",
    label: "Financial Management",
    icon: DollarSign,
    group: "Core",
    subItems: [
      { path: "/finance/chart-of-accounts", label: "Chart of Accounts", icon: BookOpen },
      { path: "/finance/transactions", label: "Journal Entries", icon: Receipt },
      { path: "/finance/invoices", label: "Invoices (AP/AR)", icon: FileText },
      { path: "/finance/budgets", label: "Budget Planning", icon: Calculator },
      { path: "/finance/payments", label: "Payment Vouchers", icon: CreditCard },
      { path: "/finance/reports", label: "Financial Reports", icon: BarChart3 },
    ],
  },
  {
    key: "crm",
    label: "CRM",
    icon: Users,
    group: "Core",
    subItems: [
      { path: "/crm/customers", label: "Customer Master", icon: Users },
      { path: "/crm/leads", label: "Lead Management", icon: UserPlus },
      { path: "/crm/interactions", label: "Interaction Log", icon: MessageSquare },
      { path: "/crm/follow-ups", label: "Follow-Up Scheduler", icon: CalendarClock },
      { path: "/crm/pipeline", label: "Sales Pipeline", icon: Kanban },
    ],
  },
  {
    key: "properties",
    label: "Property Management",
    icon: Building2,
    group: "Core",
    subItems: [
      { path: "/properties/list", label: "Property Master", icon: Building },
      { path: "/properties/units", label: "Unit Inventory", icon: Layers },
      { path: "/properties/amenities", label: "Amenities & Features", icon: Star },
      { path: "/properties/inspections", label: "Inspection Reports", icon: ClipboardCheck },
      { path: "/properties/occupancy", label: "Occupancy Dashboard", icon: PieChart },
    ],
  },

  // ==================== PROJECT LIFECYCLE ====================
  {
    key: "land",
    label: "Land Acquisition",
    icon: MapPin,
    group: "Project Lifecycle",
    subItems: [
      { path: "/land/parcels", label: "Land Parcels", icon: Map },
      { path: "/land/negotiations", label: "Negotiations", icon: Handshake },
      { path: "/land/due-diligence", label: "Due Diligence", icon: Search },
      { path: "/land/approvals", label: "Regulatory Approvals", icon: ShieldCheck },
    ],
  },
  {
    key: "procurement",
    label: "Bidding & Procurement",
    icon: Gavel,
    group: "Project Lifecycle",
    subItems: [
      { path: "/procurement/vendors", label: "Vendor Master", icon: Truck },
      { path: "/procurement/bids", label: "Bid Management", icon: FileCheck },
      { path: "/procurement/purchase-orders", label: "Purchase Orders", icon: ClipboardList },
      { path: "/procurement/grn", label: "Goods Received Notes", icon: PackageCheck },
      { path: "/procurement/comparisons", label: "Bid Comparisons", icon: BarChart },
    ],
  },
  {
    key: "construction",
    label: "Construction Mgmt",
    icon: HardHat,
    group: "Project Lifecycle",
    subItems: [
      { path: "/construction/activities", label: "Activity Tracker", icon: Activity },
      { path: "/construction/daily-logs", label: "Daily Site Logs", icon: CalendarDays },
      { path: "/construction/safety", label: "Safety Incidents", icon: ShieldAlert },
      { path: "/construction/quality", label: "Quality Inspections", icon: ClipboardCheck },
      { path: "/construction/equipment", label: "Equipment Allocation", icon: Settings },
    ],
  },
  {
    key: "controls",
    label: "Project Controls",
    icon: Gauge,
    group: "Project Lifecycle",
    subItems: [
      { path: "/controls/earned-value", label: "Earned Value Analysis", icon: TrendingUp },
      { path: "/controls/risks", label: "Risk Register", icon: AlertTriangle },
      { path: "/controls/change-orders", label: "Change Orders", icon: FileEdit },
      { path: "/controls/schedule", label: "Schedule Performance", icon: Clock },
      { path: "/controls/cost-reports", label: "Cost Reports", icon: Calculator },
    ],
  },

  // ==================== FINANCIAL & ASSET ====================
  {
    key: "assets",
    label: "Asset Management",
    icon: Package,
    group: "Financial & Asset",
    subItems: [
      { path: "/assets/register", label: "Asset Register", icon: ListChecks },
      { path: "/assets/depreciation", label: "Depreciation Schedule", icon: TrendingDown },
      { path: "/assets/maintenance", label: "Asset Maintenance", icon: Wrench },
      { path: "/assets/transfers", label: "Asset Transfers", icon: ArrowLeftRight },
    ],
  },
  {
    key: "valuations",
    label: "Property Valuation",
    icon: TrendingUp,
    group: "Financial & Asset",
    subItems: [
      { path: "/valuations/appraisals", label: "Appraisal Reports", icon: FileText },
      { path: "/valuations/market-analysis", label: "Market Analysis", icon: LineChart },
      { path: "/valuations/comparables", label: "Comparable Sales", icon: Eye },
      { path: "/valuations/history", label: "Valuation History", icon: History },
    ],
  },
  {
    key: "leases",
    label: "Lease & Rental",
    icon: KeyRound,
    group: "Financial & Asset",
    subItems: [
      { path: "/leases/agreements", label: "Lease Agreements", icon: ScrollText },
      { path: "/leases/rent-payments", label: "Rent Collection", icon: BadgeDollarSign },
      { path: "/leases/renewals", label: "Renewal Tracker", icon: CalendarRange },
      { path: "/leases/escalations", label: "Rent Escalations", icon: TrendingUp },
      { path: "/leases/arrears", label: "Arrears Report", icon: FileWarning },
    ],
  },

  // ==================== SALES & MARKETING ====================
  {
    key: "sales",
    label: "Sales Management",
    icon: ShoppingCart,
    group: "Sales & Marketing",
    subItems: [
      { path: "/sales/transactions", label: "Sales Transactions", icon: Receipt },
      { path: "/sales/payment-plans", label: "Payment Plans", icon: CreditCard },
      { path: "/sales/reservations", label: "Unit Reservations", icon: Bookmark },
      { path: "/sales/commissions", label: "Commission Tracker", icon: HandCoins },
      { path: "/sales/handovers", label: "Handover Management", icon: Flag },
    ],
  },
  {
    key: "marketing",
    label: "Marketing Automation",
    icon: Megaphone,
    group: "Sales & Marketing",
    subItems: [
      { path: "/marketing/campaigns", label: "Campaign Manager", icon: MegaphoneIcon },
      { path: "/marketing/channels", label: "Channel Performance", icon: Radio },
      { path: "/marketing/content", label: "Content Library", icon: Image },
      { path: "/marketing/analytics", label: "Marketing Analytics", icon: BarChart3 },
      { path: "/marketing/events", label: "Events & Open Houses", icon: Calendar },
    ],
  },
  {
    key: "opportunities",
    label: "Opportunity Mgmt",
    icon: Target,
    group: "Sales & Marketing",
    subItems: [
      { path: "/opportunities/pipeline", label: "Pipeline Board", icon: GitBranch },
      { path: "/opportunities/list", label: "Opportunity List", icon: ListChecks },
      { path: "/opportunities/forecasting", label: "Revenue Forecasting", icon: LineChart },
      { path: "/opportunities/win-loss", label: "Win/Loss Analysis", icon: PieChart },
    ],
  },

  // ==================== FACILITY OPERATIONS ====================
  {
    key: "facility",
    label: "Facility Operations",
    icon: Landmark,
    group: "Facility Operations",
    subItems: [
      { path: "/facility/buildings", label: "Building / Tower Registry", icon: Building2 },
      { path: "/facility/units", label: "Unit Directory", icon: DoorOpen },
      { path: "/facility/common-areas", label: "Common Areas & Facilities", icon: Droplets },
      { path: "/facility/owners", label: "Owner Management", icon: UserSquare },
      { path: "/facility/tenants", label: "Tenant Registry", icon: Contact },
      { path: "/facility/leases", label: "Lease Contracts", icon: ScrollTextFM },
      { path: "/facility/rent-collection", label: "Rent Collection", icon: Banknote },
      { path: "/facility/rent-arrears", label: "Rent Arrears & Recovery", icon: AlertOctagon },
      { path: "/facility/maintenance-requests", label: "Maintenance Requests", icon: Hammer },
      { path: "/facility/preventive-maintenance", label: "Preventive Maintenance", icon: ShieldPlus },
      { path: "/facility/vendors", label: "FM Vendors & Contractors", icon: Store },
      { path: "/facility/staff", label: "Staff Directory", icon: UserCogFM },
      { path: "/facility/staff-scheduling", label: "Staff Scheduling & Shifts", icon: CalendarClockFM },
      { path: "/facility/vacancies", label: "Vacancy Tracker", icon: EyeFM },
      { path: "/facility/listings", label: "Marketing Listings", icon: ImagePlus },
      { path: "/facility/rent-teller", label: "Rent Teller / Counter", icon: Banknote },
    ],
  },
  {
    key: "cheques",
    label: "Cheque Management",
    icon: FileCheck,
    group: "Facility Operations",
    subItems: [
      { path: "/cheques/pdc-register", label: "PDC Register", icon: ScrollTextFM },
      { path: "/cheques/deposits", label: "Cheque Deposits", icon: Banknote },
      { path: "/cheques/bounced", label: "Bounced Cheques", icon: AlertOctagon },
    ],
  },

  // ==================== ADMIN & SUPPORT ====================
  {
    key: "hr",
    label: "HCM & Payroll",
    icon: UserCog,
    group: "Admin & Support",
    subItems: [
      { path: "/hr/employees", label: "Employee Master", icon: Users },
      { path: "/hr/payroll", label: "Payroll Processing", icon: Wallet },
      { path: "/hr/attendance", label: "Attendance Tracker", icon: UserCheck },
      { path: "/hr/leave", label: "Leave Management", icon: Plane },
      { path: "/hr/recruitment", label: "Recruitment Pipeline", icon: Briefcase },
    ],
  },
  {
    key: "legal",
    label: "Legal & Compliance",
    icon: Scale,
    group: "Admin & Support",
    subItems: [
      { path: "/legal/contracts", label: "Contract Management", icon: ScrollText },
      { path: "/legal/compliance", label: "Compliance Tracker", icon: ShieldCheck },
      { path: "/legal/permits", label: "Permits & Licenses", icon: Stamp },
      { path: "/legal/disputes", label: "Dispute Resolution", icon: GavelIcon },
      { path: "/legal/noc", label: "NOC Management", icon: FileKey },
    ],
  },
  {
    key: "documents",
    label: "Document Management",
    icon: FileText,
    group: "Admin & Support",
    subItems: [
      { path: "/documents/repository", label: "Document Repository", icon: FolderOpen },
      { path: "/documents/templates", label: "Document Templates", icon: FilePlus },
      { path: "/documents/approvals", label: "Approval Workflows", icon: FileCheck },
      { path: "/documents/archive", label: "Archive", icon: FolderArchive },
    ],
  },
  {
    key: "inventory",
    label: "Inventory Management",
    icon: Boxes,
    group: "Admin & Support",
    subItems: [
      { path: "/inventory/items", label: "Item Master", icon: Package },
      { path: "/inventory/transactions", label: "Stock Movements", icon: ArrowLeftRight },
      { path: "/inventory/warehouses", label: "Warehouse Management", icon: Warehouse },
      { path: "/inventory/requisitions", label: "Material Requisitions", icon: ClipboardMinus },
      { path: "/inventory/stock-reports", label: "Stock Reports", icon: FileSpreadsheet },
    ],
  },
  {
    key: "helpdesk",
    label: "Helpdesk / Facility",
    icon: Headset,
    group: "Admin & Support",
    subItems: [
      { path: "/helpdesk/tickets", label: "Ticket Management", icon: Ticket },
      { path: "/helpdesk/maintenance", label: "Maintenance Schedule", icon: Wrench },
      { path: "/helpdesk/work-orders", label: "Work Orders", icon: ClipboardList },
      { path: "/helpdesk/sla", label: "SLA Tracking", icon: Timer },
      { path: "/helpdesk/vendors", label: "Service Vendors", icon: Truck },
    ],
  },
  {
    key: "tenants",
    label: "Tenant Portal",
    icon: Home,
    group: "Admin & Support",
    subItems: [
      { path: "/tenants/directory", label: "Tenant Directory", icon: Contact },
      { path: "/tenants/notifications", label: "Notifications", icon: Bell },
      { path: "/tenants/requests", label: "Service Requests", icon: MessageCircle },
      { path: "/tenants/statements", label: "Account Statements", icon: FileSpreadsheet },
      { path: "/tenants/community", label: "Community Board", icon: UsersRound },
    ],
  },
];

export const groups = ["Core", "Project Lifecycle", "Financial & Asset", "Sales & Marketing", "Facility Operations", "Admin & Support"];

export const dashboardItem = {
  path: "/",
  label: "Dashboard",
  icon: LayoutDashboard,
};

export const aiAssistantItem = {
  path: "/ai-assistant",
  label: "AI Assistant",
  icon: Bot,
};
