/**
 * Facility & Property Operations Module - Frontend Configs
 * 15 sub-pages with full CRUD grid definitions
 * Types: Column { key, label, sortable?, type?, width?, render?, hidden? }
 *        FieldDef { name, label, type?, required?, options?: {value,label}[], placeholder?, defaultValue?, hidden?, readOnly?, width? }
 *        DetailField { key, label, type?: "text"|"currency"|"date"|"status"|"percent"|"number" }
 *        SubPageConfig { title, description, endpoint, idField, entityName, columns, formFields, detailFields, searchPlaceholder?, breadcrumb? }
 */

import type { SubPageConfig } from "@/components/ModuleSubPage";

const opt = (vals: string[]) => vals.map(v => ({ value: v, label: v }));

// ============================================================
// 1. Building/Tower Registry
// ============================================================
export const fmBuildingsConfig: SubPageConfig = {
  title: "Building / Tower Registry",
  description: "Manage all buildings, towers, and villa compounds under facility management",
  endpoint: "/fm-buildings",
  idField: "building_id",
  entityName: "Building",
  searchPlaceholder: "Search buildings...",
  breadcrumb: { module: "Facility Operations", page: "Building Registry" },
  columns: [
    { key: "building_code", label: "Code", width: "80px" },
    { key: "building_name", label: "Building Name" },
    { key: "building_type", label: "Type", type: "badge" },
    { key: "city", label: "City" },
    { key: "area", label: "Area" },
    { key: "total_floors", label: "Floors", type: "number" },
    { key: "total_units", label: "Units", type: "number" },
    { key: "parking_slots", label: "Parking", type: "number" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "building_name", label: "Building Name", required: true },
    { name: "building_type", label: "Type", type: "select", options: opt(["Residential Tower", "Villa Compound", "Mixed Use Tower", "Commercial Tower", "Low-Rise Apartments"]) },
    { name: "building_code", label: "Code" },
    { name: "address", label: "Address", type: "textarea" },
    { name: "city", label: "City" },
    { name: "area", label: "Area/District" },
    { name: "total_floors", label: "Total Floors", type: "number" },
    { name: "total_units", label: "Total Units", type: "number" },
    { name: "year_built", label: "Year Built", type: "number" },
    { name: "total_area_sqft", label: "Total Area (sqft)", type: "number" },
    { name: "parking_slots", label: "Parking Slots", type: "number" },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "Under Construction", "Under Renovation", "Inactive"]) },
    { name: "management_start_date", label: "Management Start Date", type: "date" },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "description", label: "Description", type: "textarea" },
  ],
  detailFields: [
    { key: "building_id", label: "Building ID" },
    { key: "building_name", label: "Building Name" },
    { key: "building_type", label: "Type" },
    { key: "building_code", label: "Code" },
    { key: "address", label: "Address" },
    { key: "city", label: "City" },
    { key: "area", label: "Area" },
    { key: "total_floors", label: "Total Floors", type: "number" },
    { key: "total_units", label: "Total Units", type: "number" },
    { key: "year_built", label: "Year Built" },
    { key: "total_area_sqft", label: "Total Area (sqft)", type: "number" },
    { key: "parking_slots", label: "Parking Slots", type: "number" },
    { key: "status", label: "Status", type: "status" },
    { key: "management_start_date", label: "Mgmt Start Date", type: "date" },
    { key: "owner_id", label: "Owner ID" },
    { key: "description", label: "Description" },
  ],
};

// ============================================================
// 2. Unit Directory
// ============================================================
export const fmUnitsConfig: SubPageConfig = {
  title: "Unit Directory",
  description: "Manage all units across buildings — apartments, villas, retail spaces, offices",
  endpoint: "/fm-units",
  idField: "unit_id",
  entityName: "Unit",
  searchPlaceholder: "Search units...",
  breadcrumb: { module: "Facility Operations", page: "Unit Directory" },
  columns: [
    { key: "unit_number", label: "Unit #", width: "90px" },
    { key: "building_id", label: "Building" },
    { key: "unit_type", label: "Type", type: "badge" },
    { key: "floor_number", label: "Floor", type: "number" },
    { key: "bedrooms", label: "Beds", type: "number" },
    { key: "bathrooms", label: "Baths", type: "number" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "view_type", label: "View" },
    { key: "furnishing", label: "Furnishing" },
    { key: "annual_rent", label: "Annual Rent", type: "currency" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "building_id", label: "Building ID", type: "number", required: true },
    { name: "unit_number", label: "Unit Number", required: true },
    { name: "unit_type", label: "Unit Type", type: "select", options: opt(["Apartment", "Studio", "Penthouse", "Villa", "Townhouse", "Duplex", "Retail", "Office"]) },
    { name: "floor_number", label: "Floor Number", type: "number" },
    { name: "bedrooms", label: "Bedrooms", type: "number" },
    { name: "bathrooms", label: "Bathrooms", type: "number" },
    { name: "area_sqft", label: "Area (sqft)", type: "number" },
    { name: "balcony_area_sqft", label: "Balcony Area (sqft)", type: "number" },
    { name: "view_type", label: "View Type", type: "select", options: opt(["Sea View", "City View", "Garden View", "Marina View", "Panoramic", "Beach Front", "Pool View", "Park View"]) },
    { name: "furnishing", label: "Furnishing", type: "select", options: opt(["Furnished", "Semi-Furnished", "Unfurnished"]) },
    { name: "parking_number", label: "Parking #" },
    { name: "annual_rent", label: "Annual Rent (AED)", type: "number" },
    { name: "status", label: "Status", type: "select", options: opt(["Occupied", "Vacant", "Under Maintenance", "Reserved"]) },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "current_tenant_id", label: "Current Tenant ID", type: "number" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "unit_id", label: "Unit ID" },
    { key: "building_id", label: "Building ID" },
    { key: "unit_number", label: "Unit Number" },
    { key: "unit_type", label: "Type" },
    { key: "floor_number", label: "Floor", type: "number" },
    { key: "bedrooms", label: "Bedrooms", type: "number" },
    { key: "bathrooms", label: "Bathrooms", type: "number" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "balcony_area_sqft", label: "Balcony (sqft)", type: "number" },
    { key: "view_type", label: "View" },
    { key: "furnishing", label: "Furnishing" },
    { key: "parking_number", label: "Parking #" },
    { key: "annual_rent", label: "Annual Rent", type: "currency" },
    { key: "status", label: "Status", type: "status" },
    { key: "owner_id", label: "Owner ID" },
    { key: "current_tenant_id", label: "Tenant ID" },
  ],
};

// ============================================================
// 3. Common Areas & Facilities
// ============================================================
export const fmFacilitiesConfig: SubPageConfig = {
  title: "Common Areas & Facilities",
  description: "Manage pools, gyms, lobbies, gardens, and other shared amenities",
  endpoint: "/fm-facilities",
  idField: "facility_id",
  entityName: "Facility",
  searchPlaceholder: "Search facilities...",
  breadcrumb: { module: "Facility Operations", page: "Common Facilities" },
  columns: [
    { key: "facility_name", label: "Facility Name" },
    { key: "facility_type", label: "Type", type: "badge" },
    { key: "building_id", label: "Building" },
    { key: "location_floor", label: "Floor/Location" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "capacity", label: "Capacity", type: "number" },
    { key: "operating_hours", label: "Hours" },
    { key: "monthly_cost", label: "Monthly Cost", type: "currency" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "building_id", label: "Building ID", type: "number", required: true },
    { name: "facility_name", label: "Facility Name", required: true },
    { name: "facility_type", label: "Type", type: "select", options: opt(["Swimming Pool", "Gym", "Reception", "Recreation", "Parking", "Garden", "BBQ Area", "Meeting Room", "Sauna", "Kids Play Area"]) },
    { name: "location_floor", label: "Floor/Location" },
    { name: "area_sqft", label: "Area (sqft)", type: "number" },
    { name: "capacity", label: "Capacity", type: "number" },
    { name: "operating_hours", label: "Operating Hours" },
    { name: "status", label: "Status", type: "select", options: opt(["Operational", "Under Maintenance", "Closed", "Seasonal"]) },
    { name: "maintenance_schedule", label: "Maintenance Schedule" },
    { name: "last_inspection_date", label: "Last Inspection", type: "date" },
    { name: "monthly_cost", label: "Monthly Cost (AED)", type: "number" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "facility_id", label: "Facility ID" },
    { key: "building_id", label: "Building ID" },
    { key: "facility_name", label: "Name" },
    { key: "facility_type", label: "Type" },
    { key: "location_floor", label: "Location" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "capacity", label: "Capacity", type: "number" },
    { key: "operating_hours", label: "Hours" },
    { key: "status", label: "Status", type: "status" },
    { key: "maintenance_schedule", label: "Maintenance Schedule" },
    { key: "last_inspection_date", label: "Last Inspection", type: "date" },
    { key: "monthly_cost", label: "Monthly Cost", type: "currency" },
  ],
};

// ============================================================
// 4. Owner Management
// ============================================================
export const fmOwnersConfig: SubPageConfig = {
  title: "Owner Management",
  description: "Manage property owners, their portfolios, revenue sharing, and statements",
  endpoint: "/fm-owners",
  idField: "owner_id",
  entityName: "Owner",
  searchPlaceholder: "Search owners...",
  breadcrumb: { module: "Facility Operations", page: "Owner Management" },
  columns: [
    { key: "owner_name", label: "Owner Name" },
    { key: "owner_type", label: "Type", type: "badge" },
    { key: "company_name", label: "Company" },
    { key: "nationality", label: "Nationality" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "total_buildings", label: "Buildings", type: "number" },
    { key: "total_units", label: "Units", type: "number" },
    { key: "revenue_share_pct", label: "Rev Share %", type: "percent" },
    { key: "management_fee_pct", label: "Mgmt Fee %", type: "percent" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "owner_name", label: "Owner Name", required: true },
    { name: "owner_type", label: "Type", type: "select", options: opt(["Individual", "Corporate", "Government", "Trust"]) },
    { name: "company_name", label: "Company Name" },
    { name: "trade_license", label: "Trade License" },
    { name: "emirates_id", label: "Emirates ID" },
    { name: "passport_number", label: "Passport Number" },
    { name: "nationality", label: "Nationality" },
    { name: "email", label: "Email", type: "email" },
    { name: "phone", label: "Phone", type: "tel" },
    { name: "address", label: "Address", type: "textarea" },
    { name: "total_buildings", label: "Total Buildings", type: "number" },
    { name: "total_units", label: "Total Units", type: "number" },
    { name: "revenue_share_pct", label: "Revenue Share %", type: "number" },
    { name: "management_fee_pct", label: "Management Fee %", type: "number" },
    { name: "bank_name", label: "Bank Name" },
    { name: "bank_account", label: "Bank Account" },
    { name: "iban", label: "IBAN" },
    { name: "contract_start", label: "Contract Start", type: "date" },
    { name: "contract_end", label: "Contract End", type: "date" },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "Inactive", "Suspended"]) },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "owner_id", label: "Owner ID" },
    { key: "owner_name", label: "Name" },
    { key: "owner_type", label: "Type" },
    { key: "company_name", label: "Company" },
    { key: "trade_license", label: "Trade License" },
    { key: "emirates_id", label: "Emirates ID" },
    { key: "nationality", label: "Nationality" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "address", label: "Address" },
    { key: "total_buildings", label: "Buildings", type: "number" },
    { key: "total_units", label: "Units", type: "number" },
    { key: "revenue_share_pct", label: "Revenue Share %", type: "percent" },
    { key: "management_fee_pct", label: "Mgmt Fee %", type: "percent" },
    { key: "bank_name", label: "Bank" },
    { key: "iban", label: "IBAN" },
    { key: "contract_start", label: "Contract Start", type: "date" },
    { key: "contract_end", label: "Contract End", type: "date" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 5. Tenant Registry
// ============================================================
export const fmTenantsConfig: SubPageConfig = {
  title: "Tenant Registry",
  description: "Manage all tenants across buildings with contact details and lease status",
  endpoint: "/fm-tenants",
  idField: "tenant_id",
  entityName: "Tenant",
  searchPlaceholder: "Search tenants...",
  breadcrumb: { module: "Facility Operations", page: "Tenant Registry" },
  columns: [
    { key: "tenant_name", label: "Tenant Name" },
    { key: "tenant_type", label: "Type", type: "badge" },
    { key: "nationality", label: "Nationality" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "occupation", label: "Occupation" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "move_in_date", label: "Move In", type: "date" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "tenant_name", label: "Tenant Name", required: true },
    { name: "tenant_type", label: "Type", type: "select", options: opt(["Individual", "Family", "Corporate"]) },
    { name: "emirates_id", label: "Emirates ID" },
    { name: "passport_number", label: "Passport Number" },
    { name: "nationality", label: "Nationality" },
    { name: "email", label: "Email", type: "email" },
    { name: "phone", label: "Phone", type: "tel" },
    { name: "emergency_contact", label: "Emergency Contact" },
    { name: "emergency_phone", label: "Emergency Phone", type: "tel" },
    { name: "company_name", label: "Company" },
    { name: "occupation", label: "Occupation" },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "unit_id", label: "Unit ID", type: "number" },
    { name: "move_in_date", label: "Move In Date", type: "date" },
    { name: "move_out_date", label: "Move Out Date", type: "date" },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "Moved Out", "Evicted", "Notice Period"]) },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "tenant_id", label: "Tenant ID" },
    { key: "tenant_name", label: "Name" },
    { key: "tenant_type", label: "Type" },
    { key: "emirates_id", label: "Emirates ID" },
    { key: "passport_number", label: "Passport" },
    { key: "nationality", label: "Nationality" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "emergency_contact", label: "Emergency Contact" },
    { key: "emergency_phone", label: "Emergency Phone" },
    { key: "company_name", label: "Company" },
    { key: "occupation", label: "Occupation" },
    { key: "building_id", label: "Building ID" },
    { key: "unit_id", label: "Unit ID" },
    { key: "move_in_date", label: "Move In", type: "date" },
    { key: "move_out_date", label: "Move Out", type: "date" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 6. Lease Contracts
// ============================================================
export const fmLeasesConfig: SubPageConfig = {
  title: "Lease Contracts",
  description: "Manage lease agreements linking tenants, owners, and units with Ejari registration",
  endpoint: "/fm-leases",
  idField: "lease_id",
  entityName: "Lease Contract",
  searchPlaceholder: "Search leases...",
  breadcrumb: { module: "Facility Operations", page: "Lease Contracts" },
  columns: [
    { key: "contract_number", label: "Contract #", width: "120px" },
    { key: "tenant_id", label: "Tenant" },
    { key: "owner_id", label: "Owner" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "lease_type", label: "Type", type: "badge" },
    { key: "start_date", label: "Start", type: "date" },
    { key: "end_date", label: "End", type: "date" },
    { key: "annual_rent", label: "Annual Rent", type: "currency" },
    { key: "payment_frequency", label: "Frequency" },
    { key: "number_of_cheques", label: "Cheques", type: "number" },
    { key: "ejari_number", label: "Ejari #" },
    { key: "owner_payout_pct", label: "Owner %", type: "percent" },
    { key: "management_fee", label: "Mgmt Fee", type: "currency" },
    { key: "contract_status", label: "Status", type: "status" },
    { key: "renewal_status", label: "Renewal", type: "badge" },
  ],
  formFields: [
    { name: "contract_number", label: "Contract Number", required: true },
    { name: "tenant_id", label: "Tenant ID", type: "number", required: true },
    { name: "owner_id", label: "Owner ID", type: "number", required: true },
    { name: "building_id", label: "Building ID", type: "number", required: true },
    { name: "unit_id", label: "Unit ID", type: "number", required: true },
    { name: "lease_type", label: "Lease Type", type: "select", options: opt(["Residential", "Commercial", "Retail", "Mixed"]) },
    { name: "start_date", label: "Start Date", type: "date" },
    { name: "end_date", label: "End Date", type: "date" },
    { name: "annual_rent", label: "Annual Rent (AED)", type: "number" },
    { name: "security_deposit", label: "Security Deposit (AED)", type: "number" },
    { name: "commission", label: "Commission (AED)", type: "number" },
    { name: "payment_frequency", label: "Payment Frequency", type: "select", options: opt(["Monthly", "Quarterly", "Semi-Annual", "Annual"]) },
    { name: "number_of_cheques", label: "Number of Cheques", type: "number" },
    { name: "ejari_number", label: "Ejari Number" },
    { name: "ejari_registration_date", label: "Ejari Registration Date", type: "date" },
    { name: "owner_payout_pct", label: "Owner Payout %", type: "number" },
    { name: "management_fee", label: "Management Fee (AED)", type: "number" },
    { name: "contract_status", label: "Contract Status", type: "select", options: opt(["Active", "Expired", "Terminated", "Draft"]) },
    { name: "renewal_status", label: "Renewal Status", type: "select", options: opt(["Not Due", "Pending Renewal", "Renewed", "Non-Renewal"]) },
    { name: "special_terms", label: "Special Terms", type: "textarea" },
    { name: "signed_date", label: "Signed Date", type: "date" },
  ],
  detailFields: [
    { key: "lease_id", label: "Lease ID" },
    { key: "contract_number", label: "Contract #" },
    { key: "tenant_id", label: "Tenant ID" },
    { key: "owner_id", label: "Owner ID" },
    { key: "building_id", label: "Building ID" },
    { key: "unit_id", label: "Unit ID" },
    { key: "lease_type", label: "Lease Type" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "end_date", label: "End Date", type: "date" },
    { key: "annual_rent", label: "Annual Rent", type: "currency" },
    { key: "security_deposit", label: "Security Deposit", type: "currency" },
    { key: "commission", label: "Commission", type: "currency" },
    { key: "payment_frequency", label: "Payment Frequency" },
    { key: "number_of_cheques", label: "Cheques", type: "number" },
    { key: "ejari_number", label: "Ejari #" },
    { key: "ejari_registration_date", label: "Ejari Date", type: "date" },
    { key: "owner_payout_pct", label: "Owner Payout %", type: "percent" },
    { key: "management_fee", label: "Management Fee", type: "currency" },
    { key: "contract_status", label: "Status", type: "status" },
    { key: "renewal_status", label: "Renewal" },
    { key: "special_terms", label: "Special Terms" },
    { key: "signed_date", label: "Signed Date", type: "date" },
  ],
};

// ============================================================
// 7. Rent Collection
// ============================================================
export const fmRentCollectionConfig: SubPageConfig = {
  title: "Rent Collection",
  description: "Track rent payments, cheque deposits, and owner/company share splits",
  endpoint: "/fm-rent-collection",
  idField: "collection_id",
  entityName: "Rent Collection",
  searchPlaceholder: "Search collections...",
  breadcrumb: { module: "Facility Operations", page: "Rent Collection" },
  columns: [
    { key: "receipt_number", label: "Receipt #" },
    { key: "tenant_id", label: "Tenant" },
    { key: "owner_id", label: "Owner" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "payment_period", label: "Period" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "amount_due", label: "Amount Due", type: "currency" },
    { key: "amount_paid", label: "Amount Paid", type: "currency" },
    { key: "owner_share", label: "Owner Share", type: "currency" },
    { key: "company_share", label: "Company Share", type: "currency" },
    { key: "payment_method", label: "Method" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "lease_id", label: "Lease ID", type: "number", required: true },
    { name: "tenant_id", label: "Tenant ID", type: "number", required: true },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "unit_id", label: "Unit ID", type: "number" },
    { name: "payment_period", label: "Payment Period" },
    { name: "due_date", label: "Due Date", type: "date" },
    { name: "amount_due", label: "Amount Due (AED)", type: "number" },
    { name: "amount_paid", label: "Amount Paid (AED)", type: "number" },
    { name: "owner_share", label: "Owner Share (AED)", type: "number" },
    { name: "company_share", label: "Company Share (AED)", type: "number" },
    { name: "payment_date", label: "Payment Date", type: "date" },
    { name: "payment_method", label: "Payment Method", type: "select", options: opt(["Cheque", "Bank Transfer", "Cash", "Credit Card", "Online"]) },
    { name: "cheque_number", label: "Cheque Number" },
    { name: "bank_name", label: "Bank Name" },
    { name: "receipt_number", label: "Receipt Number" },
    { name: "status", label: "Status", type: "select", options: opt(["Paid", "Pending", "Overdue", "Partial", "Bounced"]) },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "collection_id", label: "Collection ID" },
    { key: "lease_id", label: "Lease ID" },
    { key: "tenant_id", label: "Tenant ID" },
    { key: "owner_id", label: "Owner ID" },
    { key: "building_id", label: "Building ID" },
    { key: "unit_id", label: "Unit ID" },
    { key: "payment_period", label: "Period" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "amount_due", label: "Amount Due", type: "currency" },
    { key: "amount_paid", label: "Amount Paid", type: "currency" },
    { key: "owner_share", label: "Owner Share", type: "currency" },
    { key: "company_share", label: "Company Share", type: "currency" },
    { key: "payment_date", label: "Payment Date", type: "date" },
    { key: "payment_method", label: "Method" },
    { key: "cheque_number", label: "Cheque #" },
    { key: "bank_name", label: "Bank" },
    { key: "receipt_number", label: "Receipt #" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 8. Rent Arrears & Recovery
// ============================================================
export const fmRentArrearsConfig: SubPageConfig = {
  title: "Rent Arrears & Recovery",
  description: "Track overdue rent, follow-up actions, legal notices, and eviction status",
  endpoint: "/fm-rent-arrears",
  idField: "arrear_id",
  entityName: "Arrear",
  searchPlaceholder: "Search arrears...",
  breadcrumb: { module: "Facility Operations", page: "Rent Arrears" },
  columns: [
    { key: "tenant_id", label: "Tenant" },
    { key: "owner_id", label: "Owner" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "total_overdue", label: "Total Overdue", type: "currency" },
    { key: "overdue_since", label: "Overdue Since", type: "date" },
    { key: "days_overdue", label: "Days", type: "number" },
    { key: "follow_up_action", label: "Follow-up Action" },
    { key: "legal_notice_sent", label: "Legal Notice" },
    { key: "priority", label: "Priority", type: "badge" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "tenant_id", label: "Tenant ID", type: "number", required: true },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "unit_id", label: "Unit ID", type: "number" },
    { name: "lease_id", label: "Lease ID", type: "number" },
    { name: "total_overdue", label: "Total Overdue (AED)", type: "number" },
    { name: "overdue_since", label: "Overdue Since", type: "date" },
    { name: "days_overdue", label: "Days Overdue", type: "number" },
    { name: "last_payment_date", label: "Last Payment Date", type: "date" },
    { name: "follow_up_action", label: "Follow-up Action" },
    { name: "follow_up_date", label: "Follow-up Date", type: "date" },
    { name: "legal_notice_sent", label: "Legal Notice Sent", type: "select", options: opt(["Yes", "No"]) },
    { name: "legal_notice_date", label: "Legal Notice Date", type: "date" },
    { name: "eviction_status", label: "Eviction Status", type: "select", options: opt(["None", "Pending", "In Progress", "Completed"]) },
    { name: "assigned_to", label: "Assigned To" },
    { name: "priority", label: "Priority", type: "select", options: opt(["Low", "Medium", "High", "Critical"]) },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "Escalated", "Resolved", "Written Off"]) },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "arrear_id", label: "Arrear ID" },
    { key: "tenant_id", label: "Tenant ID" },
    { key: "owner_id", label: "Owner ID" },
    { key: "building_id", label: "Building ID" },
    { key: "unit_id", label: "Unit ID" },
    { key: "lease_id", label: "Lease ID" },
    { key: "total_overdue", label: "Total Overdue", type: "currency" },
    { key: "overdue_since", label: "Overdue Since", type: "date" },
    { key: "days_overdue", label: "Days Overdue", type: "number" },
    { key: "last_payment_date", label: "Last Payment", type: "date" },
    { key: "follow_up_action", label: "Follow-up" },
    { key: "follow_up_date", label: "Follow-up Date", type: "date" },
    { key: "legal_notice_sent", label: "Legal Notice" },
    { key: "legal_notice_date", label: "Notice Date", type: "date" },
    { key: "eviction_status", label: "Eviction" },
    { key: "assigned_to", label: "Assigned To" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 9. Maintenance Requests
// ============================================================
export const fmMaintenanceRequestsConfig: SubPageConfig = {
  title: "Maintenance Requests",
  description: "Track and manage corrective and emergency maintenance requests from tenants",
  endpoint: "/fm-maintenance-requests",
  idField: "request_id",
  entityName: "Maintenance Request",
  searchPlaceholder: "Search requests...",
  breadcrumb: { module: "Facility Operations", page: "Maintenance Requests" },
  columns: [
    { key: "request_id", label: "Req #", width: "70px" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "tenant_id", label: "Tenant" },
    { key: "request_type", label: "Type", type: "badge" },
    { key: "category", label: "Category" },
    { key: "priority", label: "Priority", type: "badge" },
    { key: "status", label: "Status", type: "status" },
    { key: "reported_date", label: "Reported", type: "date" },
    { key: "assigned_technician", label: "Technician" },
    { key: "cost", label: "Cost", type: "currency" },
  ],
  formFields: [
    { name: "building_id", label: "Building ID", type: "number", required: true },
    { name: "unit_id", label: "Unit ID", type: "number" },
    { name: "tenant_id", label: "Tenant ID", type: "number" },
    { name: "request_type", label: "Request Type", type: "select", options: opt(["Corrective", "Emergency", "Cosmetic", "Upgrade"]) },
    { name: "category", label: "Category", type: "select", options: opt(["Plumbing", "Electrical", "HVAC", "Civil", "Painting", "Carpentry", "Pest Control", "Appliance", "Other"]) },
    { name: "description", label: "Description", type: "textarea", required: true },
    { name: "priority", label: "Priority", type: "select", options: opt(["Low", "Medium", "High", "Critical"]) },
    { name: "status", label: "Status", type: "select", options: opt(["Pending", "In Progress", "Completed", "Cancelled", "On Hold"]) },
    { name: "reported_date", label: "Reported Date", type: "date" },
    { name: "assigned_technician", label: "Assigned Technician" },
    { name: "assigned_staff_id", label: "Staff ID", type: "number" },
    { name: "scheduled_date", label: "Scheduled Date", type: "date" },
    { name: "completed_date", label: "Completed Date", type: "date" },
    { name: "resolution", label: "Resolution", type: "textarea" },
    { name: "cost", label: "Cost (AED)", type: "number" },
    { name: "vendor_id", label: "Vendor ID", type: "number" },
    { name: "satisfaction_rating", label: "Satisfaction (1-5)", type: "number" },
  ],
  detailFields: [
    { key: "request_id", label: "Request ID" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "tenant_id", label: "Tenant" },
    { key: "request_type", label: "Type" },
    { key: "category", label: "Category" },
    { key: "description", label: "Description" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status", type: "status" },
    { key: "reported_date", label: "Reported", type: "date" },
    { key: "assigned_technician", label: "Technician" },
    { key: "scheduled_date", label: "Scheduled", type: "date" },
    { key: "completed_date", label: "Completed", type: "date" },
    { key: "resolution", label: "Resolution" },
    { key: "cost", label: "Cost", type: "currency" },
    { key: "satisfaction_rating", label: "Rating", type: "number" },
  ],
};

// ============================================================
// 10. Preventive Maintenance
// ============================================================
export const fmPreventiveMaintenanceConfig: SubPageConfig = {
  title: "Preventive Maintenance",
  description: "Manage AMC contracts, scheduled servicing for elevators, HVAC, fire safety, etc.",
  endpoint: "/fm-preventive-maintenance",
  idField: "pm_id",
  entityName: "PM Schedule",
  searchPlaceholder: "Search PM schedules...",
  breadcrumb: { module: "Facility Operations", page: "Preventive Maintenance" },
  columns: [
    { key: "equipment_name", label: "Equipment" },
    { key: "equipment_type", label: "Type", type: "badge" },
    { key: "building_id", label: "Building" },
    { key: "location", label: "Location" },
    { key: "frequency", label: "Frequency" },
    { key: "last_service_date", label: "Last Service", type: "date" },
    { key: "next_service_date", label: "Next Service", type: "date" },
    { key: "vendor_name", label: "Vendor" },
    { key: "amc_contract_number", label: "AMC #" },
    { key: "annual_cost", label: "Annual Cost", type: "currency" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "building_id", label: "Building ID", type: "number", required: true },
    { name: "equipment_name", label: "Equipment Name", required: true },
    { name: "equipment_type", label: "Equipment Type", type: "select", options: opt(["Elevator", "HVAC", "Fire Safety", "Pool Equipment", "Generator", "Water Pump", "Electrical Panel", "CCTV", "Access Control"]) },
    { name: "location", label: "Location" },
    { name: "frequency", label: "Frequency", type: "select", options: opt(["Daily", "Weekly", "Bi-Weekly", "Monthly", "Quarterly", "Semi-Annual", "Annual"]) },
    { name: "last_service_date", label: "Last Service Date", type: "date" },
    { name: "next_service_date", label: "Next Service Date", type: "date" },
    { name: "vendor_name", label: "Vendor Name" },
    { name: "vendor_id", label: "Vendor ID", type: "number" },
    { name: "assigned_staff_id", label: "Assigned Staff ID", type: "number" },
    { name: "amc_contract_number", label: "AMC Contract #" },
    { name: "amc_expiry_date", label: "AMC Expiry Date", type: "date" },
    { name: "annual_cost", label: "Annual Cost (AED)", type: "number" },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "Expired", "Pending Renewal", "Cancelled"]) },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "pm_id", label: "PM ID" },
    { key: "building_id", label: "Building" },
    { key: "equipment_name", label: "Equipment" },
    { key: "equipment_type", label: "Type" },
    { key: "location", label: "Location" },
    { key: "frequency", label: "Frequency" },
    { key: "last_service_date", label: "Last Service", type: "date" },
    { key: "next_service_date", label: "Next Service", type: "date" },
    { key: "vendor_name", label: "Vendor" },
    { key: "amc_contract_number", label: "AMC #" },
    { key: "amc_expiry_date", label: "AMC Expiry", type: "date" },
    { key: "annual_cost", label: "Annual Cost", type: "currency" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 11. FM Vendor/Contractor Management
// ============================================================
export const fmVendorsConfig: SubPageConfig = {
  title: "FM Vendors & Contractors",
  description: "Manage facility management vendors, AMC contractors, and service providers",
  endpoint: "/fm-vendors",
  idField: "vendor_id",
  entityName: "Vendor",
  searchPlaceholder: "Search vendors...",
  breadcrumb: { module: "Facility Operations", page: "FM Vendors" },
  columns: [
    { key: "vendor_name", label: "Vendor Name" },
    { key: "vendor_type", label: "Type", type: "badge" },
    { key: "trade_license", label: "Trade License" },
    { key: "contact_person", label: "Contact Person" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "specialization", label: "Specialization" },
    { key: "rating", label: "Rating", type: "number" },
    { key: "amc_count", label: "AMCs", type: "number" },
    { key: "total_contract_value", label: "Contract Value", type: "currency" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "vendor_name", label: "Vendor Name", required: true },
    { name: "vendor_type", label: "Type", type: "select", options: opt(["AMC Contractor", "Service Provider", "Specialist", "General Contractor"]) },
    { name: "trade_license", label: "Trade License" },
    { name: "contact_person", label: "Contact Person" },
    { name: "email", label: "Email", type: "email" },
    { name: "phone", label: "Phone", type: "tel" },
    { name: "address", label: "Address", type: "textarea" },
    { name: "specialization", label: "Specialization" },
    { name: "rating", label: "Rating (1-5)", type: "number" },
    { name: "amc_count", label: "AMC Count", type: "number" },
    { name: "total_contract_value", label: "Total Contract Value (AED)", type: "number" },
    { name: "payment_terms", label: "Payment Terms", type: "select", options: opt(["Monthly", "Quarterly", "Semi-Annual", "Annual", "Per Job"]) },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "Inactive", "Blacklisted", "Pending Approval"]) },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "vendor_id", label: "Vendor ID" },
    { key: "vendor_name", label: "Name" },
    { key: "vendor_type", label: "Type" },
    { key: "trade_license", label: "Trade License" },
    { key: "contact_person", label: "Contact" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "address", label: "Address" },
    { key: "specialization", label: "Specialization" },
    { key: "rating", label: "Rating", type: "number" },
    { key: "amc_count", label: "AMCs", type: "number" },
    { key: "total_contract_value", label: "Contract Value", type: "currency" },
    { key: "payment_terms", label: "Payment Terms" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 12. Staff Directory (Guards + Maintenance)
// ============================================================
export const fmStaffConfig: SubPageConfig = {
  title: "Staff Directory (Guards & Maintenance)",
  description: "Manage security guards, maintenance technicians, cleaners, and supervisors",
  endpoint: "/fm-staff",
  idField: "staff_id",
  entityName: "Staff Member",
  searchPlaceholder: "Search staff...",
  breadcrumb: { module: "Facility Operations", page: "Staff Directory" },
  columns: [
    { key: "staff_name", label: "Name" },
    { key: "staff_type", label: "Type", type: "badge" },
    { key: "role", label: "Role" },
    { key: "nationality", label: "Nationality" },
    { key: "phone", label: "Phone" },
    { key: "assigned_building_name", label: "Building" },
    { key: "shift_pattern", label: "Shift" },
    { key: "monthly_salary", label: "Salary", type: "currency" },
    { key: "performance_rating", label: "Rating", type: "number" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "staff_name", label: "Staff Name", required: true },
    { name: "staff_type", label: "Staff Type", type: "select", options: opt(["Security Guard", "Maintenance", "Cleaning", "Supervisor", "Pool Attendant", "Receptionist"]), required: true },
    { name: "role", label: "Role", type: "select", options: opt(["Gate Guard", "Lobby Guard", "Patrol Guard", "Plumber", "Electrician", "AC Technician", "General Handyman", "Cleaner", "Supervisor", "Pool Attendant"]) },
    { name: "emirates_id", label: "Emirates ID" },
    { name: "passport_number", label: "Passport Number" },
    { name: "nationality", label: "Nationality" },
    { name: "phone", label: "Phone", type: "tel" },
    { name: "email", label: "Email", type: "email" },
    { name: "assigned_building_id", label: "Assigned Building ID", type: "number" },
    { name: "assigned_building_name", label: "Building Name" },
    { name: "shift_pattern", label: "Shift Pattern", type: "select", options: opt(["Day Shift (6AM-6PM)", "Night Shift (6PM-6AM)", "Day Shift (7AM-4PM)", "Day Shift (8AM-5PM)", "Rotating"]) },
    { name: "monthly_salary", label: "Monthly Salary (AED)", type: "number" },
    { name: "join_date", label: "Join Date", type: "date" },
    { name: "contract_expiry", label: "Contract Expiry", type: "date" },
    { name: "visa_expiry", label: "Visa Expiry", type: "date" },
    { name: "uniform_issued", label: "Uniform Issued", type: "select", options: opt(["Yes", "No"]) },
    { name: "certifications", label: "Certifications" },
    { name: "performance_rating", label: "Performance Rating (1-5)", type: "number" },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "On Leave", "Terminated", "Probation"]) },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "staff_id", label: "Staff ID" },
    { key: "staff_name", label: "Name" },
    { key: "staff_type", label: "Type" },
    { key: "role", label: "Role" },
    { key: "emirates_id", label: "Emirates ID" },
    { key: "passport_number", label: "Passport" },
    { key: "nationality", label: "Nationality" },
    { key: "phone", label: "Phone" },
    { key: "email", label: "Email" },
    { key: "assigned_building_name", label: "Building" },
    { key: "shift_pattern", label: "Shift" },
    { key: "monthly_salary", label: "Salary", type: "currency" },
    { key: "join_date", label: "Join Date", type: "date" },
    { key: "contract_expiry", label: "Contract Expiry", type: "date" },
    { key: "visa_expiry", label: "Visa Expiry", type: "date" },
    { key: "uniform_issued", label: "Uniform" },
    { key: "certifications", label: "Certifications" },
    { key: "performance_rating", label: "Rating", type: "number" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 13. Staff Scheduling & Shifts
// ============================================================
export const fmStaffSchedulingConfig: SubPageConfig = {
  title: "Staff Scheduling & Shifts",
  description: "Manage shift schedules, attendance tracking, and overtime for facility staff",
  endpoint: "/fm-staff-scheduling",
  idField: "schedule_id",
  entityName: "Schedule",
  searchPlaceholder: "Search schedules...",
  breadcrumb: { module: "Facility Operations", page: "Staff Scheduling" },
  columns: [
    { key: "staff_name", label: "Staff Name" },
    { key: "staff_type", label: "Type", type: "badge" },
    { key: "building_name", label: "Building" },
    { key: "shift_date", label: "Date", type: "date" },
    { key: "shift_start", label: "Start" },
    { key: "shift_end", label: "End" },
    { key: "shift_type", label: "Shift", type: "badge" },
    { key: "actual_check_in", label: "Check In" },
    { key: "actual_check_out", label: "Check Out" },
    { key: "hours_worked", label: "Hours", type: "number" },
    { key: "overtime_hours", label: "OT", type: "number" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "staff_id", label: "Staff ID", type: "number", required: true },
    { name: "staff_name", label: "Staff Name" },
    { name: "staff_type", label: "Staff Type", type: "select", options: opt(["Security Guard", "Maintenance", "Cleaning", "Supervisor"]) },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "building_name", label: "Building Name" },
    { name: "shift_date", label: "Shift Date", type: "date", required: true },
    { name: "shift_start", label: "Shift Start" },
    { name: "shift_end", label: "Shift End" },
    { name: "shift_type", label: "Shift Type", type: "select", options: opt(["Day", "Night", "Split", "On Call"]) },
    { name: "actual_check_in", label: "Actual Check In" },
    { name: "actual_check_out", label: "Actual Check Out" },
    { name: "hours_worked", label: "Hours Worked", type: "number" },
    { name: "overtime_hours", label: "Overtime Hours", type: "number" },
    { name: "status", label: "Status", type: "select", options: opt(["Scheduled", "Completed", "On Leave", "No Show", "Cancelled"]) },
    { name: "replacement_staff_id", label: "Replacement Staff ID", type: "number" },
    { name: "supervisor", label: "Supervisor" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "schedule_id", label: "Schedule ID" },
    { key: "staff_id", label: "Staff ID" },
    { key: "staff_name", label: "Name" },
    { key: "staff_type", label: "Type" },
    { key: "building_name", label: "Building" },
    { key: "shift_date", label: "Date", type: "date" },
    { key: "shift_start", label: "Start" },
    { key: "shift_end", label: "End" },
    { key: "shift_type", label: "Shift" },
    { key: "actual_check_in", label: "Check In" },
    { key: "actual_check_out", label: "Check Out" },
    { key: "hours_worked", label: "Hours", type: "number" },
    { key: "overtime_hours", label: "Overtime", type: "number" },
    { key: "status", label: "Status", type: "status" },
    { key: "replacement_staff_id", label: "Replacement" },
    { key: "supervisor", label: "Supervisor" },
  ],
};

// ============================================================
// 14. Vacancy Tracker
// ============================================================
export const fmVacanciesConfig: SubPageConfig = {
  title: "Vacancy Tracker",
  description: "Track vacant units, days vacant, condition, and marketing readiness",
  endpoint: "/fm-vacancies",
  idField: "vacancy_id",
  entityName: "Vacancy",
  searchPlaceholder: "Search vacancies...",
  breadcrumb: { module: "Facility Operations", page: "Vacancy Tracker" },
  columns: [
    { key: "unit_number", label: "Unit #" },
    { key: "unit_type", label: "Type", type: "badge" },
    { key: "building_id", label: "Building" },
    { key: "owner_id", label: "Owner" },
    { key: "floor_number", label: "Floor", type: "number" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "target_rent", label: "Target Rent", type: "currency" },
    { key: "last_rent", label: "Last Rent", type: "currency" },
    { key: "vacant_since", label: "Vacant Since", type: "date" },
    { key: "days_vacant", label: "Days", type: "number" },
    { key: "condition_status", label: "Condition", type: "badge" },
    { key: "listing_status", label: "Listing", type: "badge" },
    { key: "viewing_count", label: "Viewings", type: "number" },
  ],
  formFields: [
    { name: "building_id", label: "Building ID", type: "number", required: true },
    { name: "unit_id", label: "Unit ID", type: "number", required: true },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "unit_number", label: "Unit Number" },
    { name: "unit_type", label: "Unit Type", type: "select", options: opt(["Apartment", "Studio", "Penthouse", "Villa", "Townhouse", "Retail", "Office"]) },
    { name: "floor_number", label: "Floor", type: "number" },
    { name: "area_sqft", label: "Area (sqft)", type: "number" },
    { name: "target_rent", label: "Target Rent (AED)", type: "number" },
    { name: "last_rent", label: "Last Rent (AED)", type: "number" },
    { name: "vacant_since", label: "Vacant Since", type: "date" },
    { name: "days_vacant", label: "Days Vacant", type: "number" },
    { name: "last_tenant_name", label: "Last Tenant" },
    { name: "condition_status", label: "Condition", type: "select", options: opt(["Good", "Needs Refurbishment", "Under Maintenance", "Excellent"]) },
    { name: "refurbishment_needed", label: "Refurbishment Needed", type: "select", options: opt(["Yes", "No"]) },
    { name: "refurbishment_cost", label: "Refurbishment Cost (AED)", type: "number" },
    { name: "listing_status", label: "Listing Status", type: "select", options: opt(["Listed", "Not Listed", "Under Renovation", "Reserved"]) },
    { name: "assigned_broker", label: "Assigned Broker" },
    { name: "viewing_count", label: "Viewing Count", type: "number" },
    { name: "notes", label: "Notes", type: "textarea" },
  ],
  detailFields: [
    { key: "vacancy_id", label: "Vacancy ID" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "owner_id", label: "Owner" },
    { key: "unit_number", label: "Unit #" },
    { key: "unit_type", label: "Type" },
    { key: "floor_number", label: "Floor", type: "number" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "target_rent", label: "Target Rent", type: "currency" },
    { key: "last_rent", label: "Last Rent", type: "currency" },
    { key: "vacant_since", label: "Vacant Since", type: "date" },
    { key: "days_vacant", label: "Days Vacant", type: "number" },
    { key: "last_tenant_name", label: "Last Tenant" },
    { key: "condition_status", label: "Condition" },
    { key: "refurbishment_needed", label: "Refurb Needed" },
    { key: "refurbishment_cost", label: "Refurb Cost", type: "currency" },
    { key: "listing_status", label: "Listing" },
    { key: "assigned_broker", label: "Broker" },
    { key: "viewing_count", label: "Viewings", type: "number" },
  ],
};

// ============================================================
// 15. Marketing Listings
// ============================================================
export const fmListingsConfig: SubPageConfig = {
  title: "Marketing Listings",
  description: "Manage property listings on Bayut, Dubizzle, PropertyFinder, and custom portals",
  endpoint: "/fm-listings",
  idField: "listing_id",
  entityName: "Listing",
  searchPlaceholder: "Search listings...",
  breadcrumb: { module: "Facility Operations", page: "Marketing Listings" },
  columns: [
    { key: "listing_title", label: "Title" },
    { key: "unit_type", label: "Type", type: "badge" },
    { key: "bedrooms", label: "Beds", type: "number" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "asking_rent", label: "Asking Rent", type: "currency" },
    { key: "furnished", label: "Furnished" },
    { key: "portal_bayut", label: "Bayut" },
    { key: "portal_dubizzle", label: "Dubizzle" },
    { key: "portal_propertyfinder", label: "PF" },
    { key: "assigned_broker", label: "Broker" },
    { key: "views_count", label: "Views", type: "number" },
    { key: "inquiries_count", label: "Inquiries", type: "number" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "building_id", label: "Building ID", type: "number", required: true },
    { name: "unit_id", label: "Unit ID", type: "number", required: true },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "vacancy_id", label: "Vacancy ID", type: "number" },
    { name: "listing_title", label: "Listing Title", required: true },
    { name: "description", label: "Description", type: "textarea" },
    { name: "unit_type", label: "Unit Type", type: "select", options: opt(["Apartment", "Studio", "Penthouse", "Villa", "Townhouse", "Retail", "Office"]) },
    { name: "bedrooms", label: "Bedrooms", type: "number" },
    { name: "bathrooms", label: "Bathrooms", type: "number" },
    { name: "area_sqft", label: "Area (sqft)", type: "number" },
    { name: "asking_rent", label: "Asking Rent (AED)", type: "number" },
    { name: "listing_price_type", label: "Price Type", type: "select", options: opt(["Annual", "Monthly", "Per Sqft"]) },
    { name: "furnished", label: "Furnished", type: "select", options: opt(["Furnished", "Semi-Furnished", "Unfurnished"]) },
    { name: "amenities", label: "Amenities", type: "textarea" },
    { name: "portal_bayut", label: "List on Bayut", type: "select", options: opt(["Yes", "No"]) },
    { name: "portal_dubizzle", label: "List on Dubizzle", type: "select", options: opt(["Yes", "No"]) },
    { name: "portal_propertyfinder", label: "List on PropertyFinder", type: "select", options: opt(["Yes", "No"]) },
    { name: "portal_custom", label: "Custom Portal" },
    { name: "assigned_broker", label: "Assigned Broker" },
    { name: "broker_phone", label: "Broker Phone", type: "tel" },
    { name: "photo_count", label: "Photo Count", type: "number" },
    { name: "virtual_tour_url", label: "Virtual Tour URL" },
    { name: "listing_date", label: "Listing Date", type: "date" },
    { name: "expiry_date", label: "Expiry Date", type: "date" },
    { name: "views_count", label: "Views", type: "number" },
    { name: "inquiries_count", label: "Inquiries", type: "number" },
    { name: "status", label: "Status", type: "select", options: opt(["Active", "Draft", "Expired", "Rented", "Paused"]) },
  ],
  detailFields: [
    { key: "listing_id", label: "Listing ID" },
    { key: "building_id", label: "Building" },
    { key: "unit_id", label: "Unit" },
    { key: "owner_id", label: "Owner" },
    { key: "listing_title", label: "Title" },
    { key: "description", label: "Description" },
    { key: "unit_type", label: "Type" },
    { key: "bedrooms", label: "Beds", type: "number" },
    { key: "bathrooms", label: "Baths", type: "number" },
    { key: "area_sqft", label: "Area (sqft)", type: "number" },
    { key: "asking_rent", label: "Asking Rent", type: "currency" },
    { key: "listing_price_type", label: "Price Type" },
    { key: "furnished", label: "Furnished" },
    { key: "amenities", label: "Amenities" },
    { key: "portal_bayut", label: "Bayut" },
    { key: "portal_dubizzle", label: "Dubizzle" },
    { key: "portal_propertyfinder", label: "PropertyFinder" },
    { key: "assigned_broker", label: "Broker" },
    { key: "broker_phone", label: "Broker Phone" },
    { key: "photo_count", label: "Photos", type: "number" },
    { key: "virtual_tour_url", label: "Virtual Tour" },
    { key: "listing_date", label: "Listed", type: "date" },
    { key: "expiry_date", label: "Expires", type: "date" },
    { key: "views_count", label: "Views", type: "number" },
    { key: "inquiries_count", label: "Inquiries", type: "number" },
    { key: "status", label: "Status", type: "status" },
  ],
};
