/**
 * Rent Teller & Cheque Management Module - Frontend Configs
 * 4 sub-pages: Teller Transactions, PDC Register, Cheque Deposits, Bounced Cheques
 */

import type { SubPageConfig } from "@/components/ModuleSubPage";

const opt = (vals: string[]) => vals.map(v => ({ value: v, label: v }));

// ============================================================
// 1. Rent Teller / Collection Counter
// ============================================================
export const tellerTransactionsConfig: SubPageConfig = {
  title: "Rent Teller / Collection Counter",
  description: "Record rent payments at the teller counter — cash, cheque, card, or bank transfer. Generate receipts and track all collections.",
  endpoint: "/teller-transactions",
  idField: "transaction_id",
  entityName: "Teller Transaction",
  searchPlaceholder: "Search by receipt #, tenant, building...",
  breadcrumb: { module: "Facility Operations", page: "Rent Teller" },
  columns: [
    { key: "receipt_number", label: "Receipt #", width: "120px" },
    { key: "transaction_date", label: "Date", type: "date" },
    { key: "transaction_time", label: "Time" },
    { key: "tenant_name", label: "Tenant" },
    { key: "building_name", label: "Building" },
    { key: "unit_number", label: "Unit" },
    { key: "payment_for", label: "Payment For", type: "badge" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "vat_amount", label: "VAT", type: "currency" },
    { key: "total_amount", label: "Total", type: "currency" },
    { key: "payment_method", label: "Method", type: "badge" },
    { key: "teller_name", label: "Teller" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "receipt_number", label: "Receipt Number", required: true, placeholder: "RCP-2026-XXXX" },
    { name: "transaction_date", label: "Transaction Date", type: "date", required: true },
    { name: "transaction_time", label: "Time", placeholder: "HH:MM" },
    { name: "tenant_id", label: "Tenant ID", type: "number", required: true },
    { name: "tenant_name", label: "Tenant Name", required: true },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "owner_name", label: "Owner Name" },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "building_name", label: "Building Name" },
    { name: "unit_id", label: "Unit ID", type: "number" },
    { name: "unit_number", label: "Unit Number" },
    { name: "lease_id", label: "Lease ID", type: "number" },
    { name: "payment_for", label: "Payment For", type: "select", required: true, options: opt(["Rent", "Security Deposit", "Maintenance Fee", "Penalty", "Commission", "Utility", "Other"]) },
    { name: "period_from", label: "Period From", type: "date" },
    { name: "period_to", label: "Period To", type: "date" },
    { name: "amount", label: "Amount (AED)", type: "number", required: true },
    { name: "vat_amount", label: "VAT Amount (AED)", type: "number" },
    { name: "total_amount", label: "Total Amount (AED)", type: "number", required: true },
    { name: "payment_method", label: "Payment Method", type: "select", required: true, options: opt(["Cash", "Cheque", "Credit Card", "Debit Card", "Bank Transfer", "Online"]) },
    { name: "cheque_number", label: "Cheque Number", placeholder: "If paying by cheque" },
    { name: "cheque_date", label: "Cheque Date", type: "date" },
    { name: "cheque_bank", label: "Cheque Bank" },
    { name: "card_last_four", label: "Card Last 4 Digits", placeholder: "e.g. 4521" },
    { name: "card_type", label: "Card Type", type: "select", options: opt(["Visa", "Mastercard", "Amex", "Diners"]) },
    { name: "bank_reference", label: "Bank Reference #", placeholder: "For bank transfers" },
    { name: "transfer_bank", label: "Transfer Bank" },
    { name: "teller_name", label: "Teller Name", required: true },
    { name: "teller_id", label: "Teller ID" },
    { name: "counter_number", label: "Counter #", type: "select", options: opt(["C1", "C2", "C3", "C4"]) },
    { name: "remarks", label: "Remarks", type: "textarea" },
    { name: "status", label: "Status", type: "select", options: opt(["Completed", "Voided", "Pending", "Reversed"]) },
  ],
  detailFields: [
    { key: "transaction_id", label: "Transaction ID" },
    { key: "receipt_number", label: "Receipt #" },
    { key: "transaction_date", label: "Date", type: "date" },
    { key: "transaction_time", label: "Time" },
    { key: "tenant_name", label: "Tenant" },
    { key: "owner_name", label: "Owner" },
    { key: "building_name", label: "Building" },
    { key: "unit_number", label: "Unit" },
    { key: "lease_id", label: "Lease ID" },
    { key: "payment_for", label: "Payment For" },
    { key: "period_from", label: "Period From", type: "date" },
    { key: "period_to", label: "Period To", type: "date" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "vat_amount", label: "VAT", type: "currency" },
    { key: "total_amount", label: "Total", type: "currency" },
    { key: "payment_method", label: "Payment Method" },
    { key: "cheque_number", label: "Cheque #" },
    { key: "cheque_date", label: "Cheque Date", type: "date" },
    { key: "cheque_bank", label: "Cheque Bank" },
    { key: "card_last_four", label: "Card Last 4" },
    { key: "card_type", label: "Card Type" },
    { key: "bank_reference", label: "Bank Ref" },
    { key: "transfer_bank", label: "Transfer Bank" },
    { key: "currency", label: "Currency" },
    { key: "teller_name", label: "Teller" },
    { key: "teller_id", label: "Teller ID" },
    { key: "counter_number", label: "Counter" },
    { key: "remarks", label: "Remarks" },
    { key: "receipt_printed", label: "Receipt Printed" },
    { key: "voided", label: "Voided" },
    { key: "void_reason", label: "Void Reason" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 2. PDC Register (Post-Dated Cheque Register)
// ============================================================
export const pdcRegisterConfig: SubPageConfig = {
  title: "PDC Register",
  description: "Track all post-dated cheques received from tenants — on hand, deposited, cleared, bounced, or returned",
  endpoint: "/pdc-register",
  idField: "pdc_id",
  entityName: "PDC",
  searchPlaceholder: "Search by cheque #, tenant, bank...",
  breadcrumb: { module: "Cheque Management", page: "PDC Register" },
  columns: [
    { key: "cheque_number", label: "Cheque #", width: "120px" },
    { key: "cheque_date", label: "Cheque Date", type: "date" },
    { key: "bank_name", label: "Bank" },
    { key: "tenant_name", label: "Tenant" },
    { key: "building_name", label: "Building" },
    { key: "unit_number", label: "Unit" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "payment_for", label: "For", type: "badge" },
    { key: "period_covered", label: "Period" },
    { key: "received_date", label: "Received", type: "date" },
    { key: "deposit_date", label: "Deposited", type: "date" },
    { key: "clearing_date", label: "Cleared", type: "date" },
    { key: "bounce_count", label: "Bounces", type: "number" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "cheque_number", label: "Cheque Number", required: true },
    { name: "cheque_date", label: "Cheque Date", type: "date", required: true },
    { name: "bank_name", label: "Bank Name", required: true },
    { name: "branch_name", label: "Branch Name" },
    { name: "account_number", label: "Account Number" },
    { name: "tenant_id", label: "Tenant ID", type: "number", required: true },
    { name: "tenant_name", label: "Tenant Name", required: true },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "owner_name", label: "Owner Name" },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "building_name", label: "Building Name" },
    { name: "unit_id", label: "Unit ID", type: "number" },
    { name: "unit_number", label: "Unit Number" },
    { name: "lease_id", label: "Lease ID", type: "number" },
    { name: "amount", label: "Amount (AED)", type: "number", required: true },
    { name: "payment_for", label: "Payment For", type: "select", options: opt(["Rent", "Security Deposit", "Commission", "Other"]) },
    { name: "period_covered", label: "Period Covered", placeholder: "e.g. Jan-Mar 2026" },
    { name: "received_date", label: "Received Date", type: "date" },
    { name: "received_by", label: "Received By" },
    { name: "deposit_date", label: "Deposit Date", type: "date" },
    { name: "deposit_bank", label: "Deposit Bank" },
    { name: "deposit_slip_no", label: "Deposit Slip #" },
    { name: "clearing_date", label: "Clearing Date", type: "date" },
    { name: "replacement_cheque", label: "Replacement Cheque #" },
    { name: "replacement_date", label: "Replacement Date", type: "date" },
    { name: "bounce_count", label: "Bounce Count", type: "number" },
    { name: "penalty_amount", label: "Penalty Amount (AED)", type: "number" },
    { name: "remarks", label: "Remarks", type: "textarea" },
    { name: "status", label: "Status", type: "select", required: true, options: opt(["On Hand", "Deposited", "Cleared", "Bounced", "Replaced", "Cancelled", "Returned to Tenant"]) },
  ],
  detailFields: [
    { key: "pdc_id", label: "PDC ID" },
    { key: "cheque_number", label: "Cheque #" },
    { key: "cheque_date", label: "Cheque Date", type: "date" },
    { key: "bank_name", label: "Bank" },
    { key: "branch_name", label: "Branch" },
    { key: "account_number", label: "Account #" },
    { key: "tenant_name", label: "Tenant" },
    { key: "owner_name", label: "Owner" },
    { key: "building_name", label: "Building" },
    { key: "unit_number", label: "Unit" },
    { key: "lease_id", label: "Lease ID" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "payment_for", label: "Payment For" },
    { key: "period_covered", label: "Period" },
    { key: "received_date", label: "Received", type: "date" },
    { key: "received_by", label: "Received By" },
    { key: "deposit_date", label: "Deposited", type: "date" },
    { key: "deposit_bank", label: "Deposit Bank" },
    { key: "deposit_slip_no", label: "Deposit Slip #" },
    { key: "clearing_date", label: "Cleared", type: "date" },
    { key: "replacement_cheque", label: "Replacement Cheque" },
    { key: "replacement_date", label: "Replacement Date", type: "date" },
    { key: "bounce_count", label: "Bounces", type: "number" },
    { key: "last_bounce_date", label: "Last Bounce", type: "date" },
    { key: "last_bounce_reason", label: "Bounce Reason" },
    { key: "penalty_amount", label: "Penalty", type: "currency" },
    { key: "penalty_collected", label: "Penalty Collected" },
    { key: "remarks", label: "Remarks" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 3. Cheque Deposits
// ============================================================
export const chequeDepositsConfig: SubPageConfig = {
  title: "Cheque Deposits",
  description: "Manage cheque deposit batches — track deposits to bank, clearing status, and bounced cheques",
  endpoint: "/cheque-deposits",
  idField: "deposit_id",
  entityName: "Cheque Deposit",
  searchPlaceholder: "Search by batch #, bank, slip #...",
  breadcrumb: { module: "Cheque Management", page: "Cheque Deposits" },
  columns: [
    { key: "deposit_batch_no", label: "Batch #", width: "120px" },
    { key: "deposit_date", label: "Deposit Date", type: "date" },
    { key: "bank_name", label: "Bank" },
    { key: "deposit_slip_no", label: "Slip #" },
    { key: "total_cheques", label: "Cheques", type: "number" },
    { key: "total_amount", label: "Total Amount", type: "currency" },
    { key: "deposited_by", label: "Deposited By" },
    { key: "expected_clearing", label: "Expected Clear", type: "date" },
    { key: "actual_clearing", label: "Actual Clear", type: "date" },
    { key: "cleared_amount", label: "Cleared", type: "currency" },
    { key: "bounced_count", label: "Bounced", type: "number" },
    { key: "bounced_amount", label: "Bounced Amt", type: "currency" },
    { key: "building_name", label: "Building" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "deposit_batch_no", label: "Batch Number", required: true, placeholder: "DEP-2026-XXX" },
    { name: "deposit_date", label: "Deposit Date", type: "date", required: true },
    { name: "bank_name", label: "Bank Name", required: true },
    { name: "branch_name", label: "Branch Name" },
    { name: "deposit_slip_no", label: "Deposit Slip #" },
    { name: "total_cheques", label: "Total Cheques", type: "number" },
    { name: "total_amount", label: "Total Amount (AED)", type: "number", required: true },
    { name: "deposited_by", label: "Deposited By", required: true },
    { name: "cheque_numbers", label: "Cheque Numbers", type: "textarea", placeholder: "Comma-separated cheque numbers" },
    { name: "pdc_ids", label: "PDC IDs", placeholder: "Comma-separated PDC IDs" },
    { name: "expected_clearing", label: "Expected Clearing Date", type: "date" },
    { name: "actual_clearing", label: "Actual Clearing Date", type: "date" },
    { name: "cleared_amount", label: "Cleared Amount (AED)", type: "number" },
    { name: "bounced_count", label: "Bounced Count", type: "number" },
    { name: "bounced_amount", label: "Bounced Amount (AED)", type: "number" },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "building_name", label: "Building Name" },
    { name: "remarks", label: "Remarks", type: "textarea" },
    { name: "status", label: "Status", type: "select", required: true, options: opt(["Pending", "Partially Cleared", "Fully Cleared", "Bounced"]) },
  ],
  detailFields: [
    { key: "deposit_id", label: "Deposit ID" },
    { key: "deposit_batch_no", label: "Batch #" },
    { key: "deposit_date", label: "Deposit Date", type: "date" },
    { key: "bank_name", label: "Bank" },
    { key: "branch_name", label: "Branch" },
    { key: "deposit_slip_no", label: "Slip #" },
    { key: "total_cheques", label: "Total Cheques", type: "number" },
    { key: "total_amount", label: "Total Amount", type: "currency" },
    { key: "deposited_by", label: "Deposited By" },
    { key: "cheque_numbers", label: "Cheque Numbers" },
    { key: "pdc_ids", label: "PDC IDs" },
    { key: "expected_clearing", label: "Expected Clearing", type: "date" },
    { key: "actual_clearing", label: "Actual Clearing", type: "date" },
    { key: "cleared_amount", label: "Cleared Amount", type: "currency" },
    { key: "bounced_count", label: "Bounced Count", type: "number" },
    { key: "bounced_amount", label: "Bounced Amount", type: "currency" },
    { key: "building_name", label: "Building" },
    { key: "remarks", label: "Remarks" },
    { key: "status", label: "Status", type: "status" },
  ],
};

// ============================================================
// 4. Bounced Cheques
// ============================================================
export const bouncedChequesConfig: SubPageConfig = {
  title: "Bounced Cheques",
  description: "Track bounced cheques, recovery actions, replacement cheques, penalties, and legal proceedings",
  endpoint: "/bounced-cheques",
  idField: "bounce_id",
  entityName: "Bounced Cheque",
  searchPlaceholder: "Search by cheque #, tenant, reason...",
  breadcrumb: { module: "Cheque Management", page: "Bounced Cheques" },
  columns: [
    { key: "cheque_number", label: "Cheque #", width: "120px" },
    { key: "cheque_date", label: "Cheque Date", type: "date" },
    { key: "cheque_amount", label: "Amount", type: "currency" },
    { key: "bank_name", label: "Bank" },
    { key: "tenant_name", label: "Tenant" },
    { key: "building_name", label: "Building" },
    { key: "unit_number", label: "Unit" },
    { key: "bounce_date", label: "Bounce Date", type: "date" },
    { key: "bounce_reason", label: "Reason", type: "badge" },
    { key: "penalty_amount", label: "Penalty", type: "currency" },
    { key: "total_recovery", label: "Total Recovery", type: "currency" },
    { key: "replacement_cheque", label: "Replacement" },
    { key: "legal_action", label: "Legal Action", type: "badge" },
    { key: "assigned_to", label: "Assigned To" },
    { key: "status", label: "Status", type: "status" },
  ],
  formFields: [
    { name: "pdc_id", label: "PDC ID", type: "number" },
    { name: "cheque_number", label: "Cheque Number", required: true },
    { name: "cheque_date", label: "Cheque Date", type: "date", required: true },
    { name: "cheque_amount", label: "Cheque Amount (AED)", type: "number", required: true },
    { name: "bank_name", label: "Bank Name", required: true },
    { name: "tenant_id", label: "Tenant ID", type: "number", required: true },
    { name: "tenant_name", label: "Tenant Name", required: true },
    { name: "owner_id", label: "Owner ID", type: "number" },
    { name: "building_id", label: "Building ID", type: "number" },
    { name: "building_name", label: "Building Name" },
    { name: "unit_id", label: "Unit ID", type: "number" },
    { name: "unit_number", label: "Unit Number" },
    { name: "bounce_date", label: "Bounce Date", type: "date", required: true },
    { name: "bounce_reason", label: "Bounce Reason", type: "select", required: true, options: opt(["Insufficient Funds", "Account Closed", "Signature Mismatch", "Stop Payment", "Stale Cheque", "Post-Dated", "Refer to Drawer", "Other"]) },
    { name: "bounce_charges", label: "Bounce Charges (AED)", type: "number" },
    { name: "penalty_amount", label: "Penalty Amount (AED)", type: "number" },
    { name: "total_recovery", label: "Total Recovery (AED)", type: "number" },
    { name: "notification_date", label: "Notification Date", type: "date" },
    { name: "notification_method", label: "Notification Method", type: "select", options: opt(["Phone", "Email", "SMS", "Letter", "In Person"]) },
    { name: "tenant_response", label: "Tenant Response", type: "textarea" },
    { name: "replacement_cheque", label: "Replacement Cheque #" },
    { name: "replacement_date", label: "Replacement Date", type: "date" },
    { name: "replacement_amount", label: "Replacement Amount (AED)", type: "number" },
    { name: "cash_recovery", label: "Cash Recovery (AED)", type: "number" },
    { name: "recovery_date", label: "Recovery Date", type: "date" },
    { name: "legal_action", label: "Legal Action", type: "select", options: opt(["None", "Warning Sent", "Legal Notice", "Police Case", "Court Case"]) },
    { name: "legal_reference", label: "Legal Reference #" },
    { name: "assigned_to", label: "Assigned To" },
    { name: "follow_up_date", label: "Follow-up Date", type: "date" },
    { name: "remarks", label: "Remarks", type: "textarea" },
    { name: "status", label: "Status", type: "select", required: true, options: opt(["Open", "Replaced", "Recovered", "Legal", "Written Off", "Closed"]) },
  ],
  detailFields: [
    { key: "bounce_id", label: "Bounce ID" },
    { key: "pdc_id", label: "PDC ID" },
    { key: "cheque_number", label: "Cheque #" },
    { key: "cheque_date", label: "Cheque Date", type: "date" },
    { key: "cheque_amount", label: "Amount", type: "currency" },
    { key: "bank_name", label: "Bank" },
    { key: "tenant_name", label: "Tenant" },
    { key: "building_name", label: "Building" },
    { key: "unit_number", label: "Unit" },
    { key: "bounce_date", label: "Bounce Date", type: "date" },
    { key: "bounce_reason", label: "Reason" },
    { key: "bounce_charges", label: "Bounce Charges", type: "currency" },
    { key: "penalty_amount", label: "Penalty", type: "currency" },
    { key: "total_recovery", label: "Total Recovery", type: "currency" },
    { key: "notification_date", label: "Notified", type: "date" },
    { key: "notification_method", label: "Notification Method" },
    { key: "tenant_response", label: "Tenant Response" },
    { key: "replacement_cheque", label: "Replacement Cheque" },
    { key: "replacement_date", label: "Replacement Date", type: "date" },
    { key: "replacement_amount", label: "Replacement Amount", type: "currency" },
    { key: "cash_recovery", label: "Cash Recovery", type: "currency" },
    { key: "recovery_date", label: "Recovery Date", type: "date" },
    { key: "legal_action", label: "Legal Action" },
    { key: "legal_reference", label: "Legal Ref" },
    { key: "assigned_to", label: "Assigned To" },
    { key: "follow_up_date", label: "Follow-up", type: "date" },
    { key: "remarks", label: "Remarks" },
    { key: "status", label: "Status", type: "status" },
  ],
};
